baseURL = "/"
languageCode = "en-us"
title = "EBFE (JMP -2)"
uglyURLs = true
theme = "hugo_theme_pickles"
PygmentsCodeFences = true
PygmentsStyle = "native"

[params]
  paginate = 10
  linkedin = "santrancisco"
  github = "santrancisco"
  disqus = "ebfepw"
  avatar = "/static/ebfe.png"
  author = "San Tran"
  bio = "Father of 2 awesome kids"
  subtitle="{Passion : ['Security','Devops'],Love : ['Electronic', 'Space','Science shitz', 'moonshot ideas','Family']}"
  logo = "/static/ebfe.png"
  # Google Analytics API key.
  ga_api_key = "UA-138219541-1"
  favicon = "/static/ebfe.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true